# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and push image to Docker Hub

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Fastfood Image Version'     
        required: true

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build the docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: thiagoluis88/fastfood-app:${{ github.event.inputs.version }}